// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxsALTn2DBVV_nNSwZMogzI8W2HLysdps',
    appId: '1:157803033892:web:4ba370dea71001ad2c6fb1',
    messagingSenderId: '157803033892',
    projectId: 'grouploan-332c9',
    authDomain: 'grouploan-332c9.firebaseapp.com',
    storageBucket: 'grouploan-332c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSIbtKSzUgfCX1tRdVPoDAHCi7gFpBHx4',
    appId: '1:157803033892:android:c5d7de047a90202c2c6fb1',
    messagingSenderId: '157803033892',
    projectId: 'grouploan-332c9',
    storageBucket: 'grouploan-332c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKqlOblDblUmHQasPnxfcYBz677bv7vss',
    appId: '1:157803033892:ios:b6d412a2a80110e62c6fb1',
    messagingSenderId: '157803033892',
    projectId: 'grouploan-332c9',
    storageBucket: 'grouploan-332c9.appspot.com',
    iosClientId: '157803033892-cjv90rvmfjcdfdhqmj7c71relisgdmt4.apps.googleusercontent.com',
    iosBundleId: 'com.notifyafrica.groupLoan',
  );
}
